#!/bin/sh /etc/rc.common

START=91

start() {
  echo "config interface 'loopback'
    option ifname 'lo'
    option proto 'static'
    option ipaddr '127.0.0.1'
    option netmask '255.0.0.0'

config interface 'lan'
    option type 'bridge'
    option ifname 'eth0'
    option proto 'static'
    option ipaddr '$UU_LAN_IPADDR'
    option gateway '$UU_LAN_GATEWAY'
    option netmask '$UU_LAN_NETMASK'
    list dns '$UU_LAN_DNS'" > /etc/config/network
  /etc/init.d/network restart

  uci set dhcp.lan.ignore=1
  uci commit dhcp
  /etc/init.d/dnsmasq restart

  # 网易 UU：增加持久化检测
  # 如果检测到 monitor 脚本已存在，说明已经安装过，直接运行；否则下载安装
  if [ ! -f "/usr/sbin/uu/uuplugin_monitor.sh" ]; then
      wget https://uurouter.gdl.netease.com/uuplugin-script/openwrt/v1/install.sh -O /root/uuinstall.sh
      /bin/sh /root/uuinstall.sh openwrt $(uname -m)
  else
      /usr/sbin/uu/uuplugin_monitor.sh &
  fi

  # 迅游：增加持久化检测
  # 检测守护脚本是否存在，不存在则下载安装
#   if [ ! -f "/xunyou/xunyou_daemon.sh" ]; then
#       wget http://partnerdownload.xunyou.com/routerplugin/install.sh -O /root/xyinstall.sh
#       /bin/sh /root/xyinstall.sh openwrt $(uname -m)
#   else
#       # 迅游安装后通常通过守护脚本拉起
#       /bin/sh /xunyou/xunyou_daemon.sh simple &
#   fi

  # 奇游持久化检测
  if [ ! -f "/etc/qy/qy_acc.sh" ]; then
      # 如果文件不存在，下载并执行安装
      wget http://static.qiyou.cn/upgrade/ljb/plugin/qyplug.sh -O /tmp/qyplug.sh && sh /tmp/qyplug.sh
  else
      # 如果文件存在，先用 sed 修正其中的 curl 下载指令
      sed -i 's/get_qyplug="curl -s -k -L -m 30 \\"${url}\\" -o \\"${sh_file}\\""/get_qyplug="wget --no-check-certificate -T 30 \\"${url}\\" -O \\"${sh_file}\\""/' /etc/qy/qy_acc.sh
      # 然后启动加速器
      /etc/qy/qy_acc.sh start &
  fi

  if [ -n "$GOSTAPI" ]; then
    /usr/bin/gost -api :"$GOSTAPI" >/dev/null 2>&1 &
  fi
}
